<<<<<<< HEAD
<<<<<<< HEAD
version: '3'

services:

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    env_file:
      - ./.env
    restart: always
    expose:
      - 3000
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      areanet:
        ipv4_address: 172.16.0.2
    healthcheck:
      test: curl -fSs 127.0.0.1:3000/api/v1/health || exit 1
      interval: 20s
      timeout: 10s
      retries: 3

  gitea_db:
    image: postgres:14
    container_name: gitea_database
    env_file:
      - ./.env.db
    restart: always
    expose:
      - 5432
    volumes:
      - ./gitea_database:/var/lib/postgresql/data
    networks:
      areanet:
        ipv4_address: 172.16.0.3
    healthcheck:
      test: pg_isready
      interval: 20s
      timeout: 5s
      retries: 3

networks:
  areanet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/28"
=======
version: '3'

services:

  gitea:
    image: gitea/gitea:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - areanet
    healthcheck:
      test: curl -fSs localhost:3000 || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

  gitea_db:
    image: postgres:14
    container_name: gitea_database
    env_file:
      - ./.env.db
    restart: always
    expose:
      - 5432
    volumes:
      - ./gitea_database:/var/lib/postgresql/data
    networks:
      - areanet
    healthcheck:
      test: pg_isready
      interval: 60s
      timeout: 5s
      retries: 3

networks:
  areanet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/28"
>>>>>>> 49d95b7 (update)
=======
version: '3'

services:

  gitea:
    image: gitea/gitea:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - areanet
    healthcheck:
      test: curl -fSs localhost:3000 || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

  gitea_db:
    image: postgres:14
    container_name: gitea_database
    env_file:
      - ./.env.db
    restart: always
    expose:
      - 5432
    volumes:
      - ./gitea_database:/var/lib/postgresql/data
    networks:
      - areanet
    healthcheck:
      test: pg_isready
      interval: 60s
      timeout: 5s
      retries: 3

networks:
  areanet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/28"
>>>>>>> f73f4cc (update: Readme.md)
